### ISSUE TITLE
script pipeline_huggingfaces.sh overwrite existing key.json

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#10]
As the title says. Script should check whether file exists and only if it doesn't copy the template over. As it is, it will overwrite any existing file, potentially destroying information.

**Comment by phisad** [comment]
I think it would be save to assume that the user has already prepared the key.json and simply remove that line of code.

**Comment by Gnurro** [comment]
https://github.com/clp-research/clembench/pull/13

**Comment by Gnurro** [comment]
The current huggingface pipeline script does nothing with key.json anymore, and the corresponding backend does not use key.json.
The HF Llama2 script does check for key.json and notifies the user if it is missing, as the backend needs a viable HF access token to download the weights: https://github.com/clp-research/clembench/blob/f4c457ed5557d8a22b16c046e84024625bd070a4/pipeline_llama2_hf.sh#L5-L11
