### ISSUE TITLE
overhaul documentation on how to add games

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#11]
This is woefully incomplete at the moment. It would be good if this could be broken down in smaller steps, for example talking us through the implementation of the hellogame. At the moment, the logic of how a game is executed is distributed over so many places, it is very difficult to get a way into the code. 

It would be good to follow the flow of execution here: what does actually happen when `cli.py` runs a game? (For example, the main loop, if I'm understanding this right, is the `play()` method of `DialogueGameMaster`. But I doubt that anyone coming to this code fresh has a chance of indentifying that.

**Comment by davidschlangen** [comment]
Where are we on this? Documentation has improved dramatically -- close the issue?

**Comment by davidschlangen** [comment]
@briemadu ⬆️

**Comment by briemadu** [comment]
The [example notebook](https://github.com/clp-research/clembench/blob/main/docs/howto_add_games_example.ipynb) is finished. @phisad can confirm if [howto_add_games.md](https://github.com/clp-research/clembench/blob/main/docs/howto_add_games.md) is also ready.
