### ISSUE TITLE
[wordle] Context limit exceeding not handled properly

### ISSUE THREAD

**Issue by Gnurro** [clp-research/clemcore#122]
The changes added in https://github.com/clp-research/clembench/commit/113c03bf97f50af74cf6e1c1d57ac1a89ba02f04# are not sufficient to properly handle context limits.

I tried running Pharia models (https://huggingface.co/Aleph-Alpha/Pharia-1-LLM-7B-control-hf), using a adapted HF backend to make them work, and while they play other games fine, wordle gets stuck in an endless loop. This comes with exceeding the context limit by extreme margins - it hit 1782851 token inputs while the limit is 8192, and wordle just kept adding more. I had to stop that run manually as it was looping for more then twelve hours.

If a ContextExceededError is caught, the input context created by a clemgame should either be culled to not exceed the limit or the episode should simply be aborted. This is left to clemgame developers as the intended way to cull context is to remove a fitting number of messages from the message history - and since different clemgames handle prompting and multiple roles differently, this can't be done in a general fashion.

**Comment by Gnurro** [comment]
Tagging @kranti-up for feedback.

**Comment by davidschlangen** [comment]
But as far as I know, nothing has changed in the world code in the meantime? So it looks like this extreme growth of the context comes from the new mechanism rathern, no?

**Comment by Gnurro** [comment]
It came up with a specific model, which somehow produced a loop - I do not know the wordle code well enough to know what lead to that, but it's how I found out that ContextExceededError is caught in the wordle code, but not actually handled - it just goes on looping despite having exceeded the model's context by a large margin. We have the error to prevent exactly this.

**Comment by davidschlangen** [comment]
What is the status of this?

**Comment by kranti-up** [comment]
I am yet to test with this specific model and debug the error. Planning to complete this week.

**Comment by kranti-up** [comment]
1. There was an issue in handling the retry for critic errors which lead to the context exceeding error
2. The context exceeding error was not handled in the critic response, with the assumption that retry would take care of it. 

Commit bf3ba52 contains the fix, and the game flow should now work as intended
