### ISSUE TITLE
use global variables instead of strings in openai backend

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#19]
https://github.com/clp-research/clembench/blob/213f184e8dfbcc107a7dc868b6e1c52ef09d4eba/backends/openai_api.py#L28

Should this not use SUPPORTED_MODELS rather than listing the model names again? Adding a new model would mean adding this information at more than one place, I think; would be better if there's only one.

**Comment by davidschlangen** [comment]
Ah hang on, it's a subset of SUPPORTED_MODELS. But in any case, should then get a global variable as well, so that all this information is in the header.

**Comment by davidschlangen** [comment]
Whatever was the case here, this is going to be addressed by #26 . Closing for now.

**Comment by phisad** [comment]
Btw. the "model_type" might be noted in the OpenAI ModelSpecs of the registiry e.g. {"model_type":"chat"} This will be then available via the ModelSpec.opts attribute
