### ISSUE TITLE
max tokens in backends should not be hardcoded

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#20]
It looks like all backends (or at least the ones I've looked at, openai ~~and huggingface_local~~), hardcode the maximal number of tokens to be returned **in the call to `generate()`, as a number**. At the very least, this should be a global variable at the beginning of the file, but ideally, it should be a parameter that can be set from the outside.

**Comment by Gnurro** [comment]
The huggingface_local backend does not hardcode max tokens - the generation method can be passed any integer, it just defaults to 100: https://github.com/clp-research/clembench/blob/b978765263064052a4e911a57b8737555ebbd77a/backends/huggingface_local_api.py#L134
The standard value could be set as an attribute like temperature is, if that's the issue.
EDIT: This is the same for the llama2_hf_local backend.

**Comment by davidschlangen** [comment]
True. But the openai one does.

**Comment by phisad** [comment]
Fixed with #47
