### ISSUE TITLE
[backend] decision about switching to some library that provides wrapper around accessing open-weight models locally

### ISSUE THREAD

**Issue by sherzod-hakimov** [clp-research/clemcore#30]
Potential libraries:

- [ollama](https://github.com/jmorganca/ollama/tree/main)
- [vllm](https://github.com/vllm-project/vllm)
- [openllm](https://github.com/bentoml/OpenLLM)
- [fastchat](https://github.com/lm-sys/FastChat/)

**Comment by davidschlangen** [comment]
Clarify title? In what sense do we want to *switch*? Have we not committed to running local models directly? (That is, the backend is the transformers object.)

As far as I am aware, there is this independent issue of wanting to provide a (locally running, "free") API for explorative work. But the idea is not (necessarily) for the clembench runs to make use of this service, e.g., to run Llamas. Or is it?

**Comment by davidschlangen** [comment]
Looks like we've decided on FastChat? Close?
