### ISSUE TITLE
[enhancement] Suppress backend warnings when running experiments

### ISSUE THREAD

**Issue by lpfennigschmidt** [clp-research/clemcore#50]
As a game developer, I would like to suppress backend warnings that I am not responsible for, so that I have a clean shell output when I run experiments.

Some examples:
- openchat_3.5, Mistral-7B-Instruct-v0.1, and CodeLlama-34b-Instruct-hf output this:
![Screenshot 2024-02-19 at 11 31 47](https://github.com/clp-research/clembench/assets/49560512/5b7dc863-f869-4060-a440-a53675f44a6b)
- Yi-Chat throws a warning that do_sample is set to False but the temperature and top_p is set to something other than 0 which mismatches
- sheep-duck-llama does not output any warning ✅

**Comment by phisad** [comment]
Does Huggingfaces already provide an option to suppress these warnings?

**Comment by Gnurro** [comment]
> Does Huggingfaces already provide an option to suppress these warnings?

Not specifically. The common solution is to just set the pad_token_id to the tokenizer's eos_token_id in code.
It's on my list of small fixes to the HF backend, which I plan to implement once the major model registry refactor is done.
It's also a legacy leftover in `transformers` which has no actual effect on any model we are using - the warning spam can be annoying, though.

**Comment by phisad** [comment]
@Gnurro big refactoring is done; so you could now proceed with this?

**Comment by Gnurro** [comment]
https://github.com/clp-research/clembench/pull/59

**Comment by phisad** [comment]
Is this fixed with https://github.com/clp-research/clembench/pull/59 @lpfennigschmidt ?

**Comment by sherzod-hakimov** [comment]
It still exists.

**Comment by Gnurro** [comment]
Which models do still give the warnings? I can look into those specifically to see why my generic solution doesn't work for them.

**Comment by sherzod-hakimov** [comment]
I see it with Mixtral.

**Comment by sherzod-hakimov** [comment]
I don't know about other models but I think I saw it with others as well.

**Comment by Gnurro** [comment]
https://github.com/clp-research/clembench/pull/75 should finally fix this. The `pad_token_id` needs to ultimately be set on a model's `generation_config`, not just the tokenizer. (It still may need to be set on the tokenizer before if that's not set properly as well.)
