### ISSUE TITLE
[backend] Missing Huggingface backend logging

### ISSUE THREAD

**Issue by Gnurro** [clp-research/clemcore#63]
After the model registry/v1.0beta update, none of the logger calls in `backends/huggingface_local_api.py` work anymore. This is an issue for properly running the benchmark using that backend and testing added models.
Logging code in  `huggingface_local_api.py` has not changed, so I suspect the logger initialization or passing the `name` argument in  `backends/__init__.py` is the cause.

**Comment by phisad** [comment]
Works actually as intended, but backend logging might be adjusted in the logging.yaml to fulfil the new requirement.

```diff
loggers:
  benchmark.run:
    handlers: [ console ]
  backends:
    level: DEBUG
+   handlers: [ console, file_handler ]
```

Outputs:
```
2024-03-04 13:48:07,060 - backends.huggingface_local_api - INFO - Loading huggingface model config and tokenizer: llama-2-7b-chat-hf
```
to console and clembench.log when calling 
```    
def test_get_model_for_huggingface_local_logs_infos(self):
        load_model_registry()
        get_model_for("llama-2-7b-chat-hf")
```

**Comment by phisad** [comment]
I commited the change above. Does it work now for you @Gnurro ?

**Comment by Gnurro** [comment]
Yes, the backend info-level logging works as I've been used to again.
