### ISSUE TITLE
make path for results configurable

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#7]
The path where the episode transcripts are written should be configurable (for `cli.py`, or maybe more generally). Some people may prefer a location outside of the code repo.

**Comment by davidschlangen** [comment]
@briemadu, this has been done, right? Close?

**Comment by briemadu** [comment]
Right, done in a177c1ddc30857e355c6099e6412f4fcd9bf2344 with a fix by SH fbed0c4858a0ffa4099eff4012836d2f13c83ebd .

**Comment by briemadu** [comment]
@phisad this should also be done for the main cli

**Comment by phisad** [comment]
Fixed with https://github.com/clp-research/clembench/pull/66
