### ISSUE TITLE
[games] claude models seem to have problem with taboo

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#76]
clembench 1.0 taboo ran with claude 1 and 2; clembench 1.5 taboo does not seem to run anymore. The good old problem of two consecutive "user" role messages (which we had with private/shared), which the API is rejecting.

**Comment by Gnurro** [comment]
I will likely make the cleaning function written for the HF backend a general backend utility with the llama.cpp backend, so it could be used in other backends like the one that covers Claude as well.

**Comment by phisad** [comment]
see PR #77
