### ISSUE TITLE
Double model loading/initialization

### ISSUE THREAD

**Issue by Gnurro** [clp-research/clemcore#85]
With the latest version (as of April 25.), the main log (clembench.log) has double log entries for model loading. This is happening with at least privateshared and wordle. This is likely the cause for memory issues I encountered on a current run of the full benchmark: Inference is very slow (likely due to offloading to RAM/drive), and at least one model crashed with out-of-memory errors.
As far as I know the double loading is new, as I did not see the double log entries on earlier runs (which also were as fast as the hardware makes me expect).
I don't have the time to properly investigate this for now, but I suspect this is due to some change in Player/game initialization, with two different Player (subclass) instances each loading the same model. Instead all Players with the same model should use one single instance of Model.

**Comment by Gnurro** [comment]
The performance issues might have been a fluke, and the misleading logging should be fixed with https://github.com/clp-research/clembench/commit/afccf94fece3e57735b21d7b56635cbec2b15b1e . It might be good if someone double-checks this, but I think the issue can be closed.

**Comment by davidschlangen** [comment]
Have you observed any more performance problems, @Gnurro ?  If not, we can close -- @phisad ?

**Comment by phisad** [comment]
Can be closed as stated above
