### ISSUE TITLE
improve tokenizer in taboo

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#9]
I just saw a game where the clue 

> A term that refers to the act of completing a task without professional help

allegedly contains the taboo words "diy, do, it, yourself".  My only explanation is that "without" created a hit for "it" -- which is not what the rules should be. The test should be for there being a *token*, not for string inclusion.

**Comment by phisad** [comment]
Fixed with https://github.com/clp-research/clembench/pull/57 (see test_clue_check_issue9 test case)
