### ISSUE TITLE
[image game] INSTRUCTION not a good label?

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#94]
Investigate whether using (for example) "command" instead of "instruction" as response parsing label removes spurious output by some of the bigger models, which might get confused because that's used in the instruction tuning...

**Comment by Gnurro** [comment]
It's probably a good idea to avoid things commonly used in instruction/chat-tuning. Aside from 'instruction', 'assistant' and 'user' are very common.
I could collect the chat templates for the models we have in our model registry and their corresponding tag token strings, for reference during game development.

**Comment by davidschlangen** [comment]
@Gnurro , yes that would be helpful!

**Comment by davidschlangen** [comment]
@sherzod-hakimov , can this be closed?

**Comment by Gnurro** [comment]
I still plan to create a document on template tags/special tokens and potentially some utility scripts to dynamically handle this based on model registry entries, although that's a bigger scope than just imagegame.
